runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  # Static file handling (e.g., CSS, JavaScript, images)
  - url: /static
    static_dir: static

  # This handles all other URLs
  - url: /.*
    script: auto

env_variables:
  PYTHONUNBUFFERED: "true"
